markdown:         kramdown
highlighter:      rouge
permalink:        /blog/:year/:month/:day/:title
title:            Anthony Lloyd
tagline:          'functional thoughts'
description:      'A few of my own ideas on functional programming'
url:              http://anthonylloyd.github.io
baseurl:          /
author:           Anthony Lloyd
  name:           Anthony Lloyd
  url:            http://anthonylloyd.github.io
github:           AnthonyLloyd123
  repo:           http://anthonylloyd.github.io
