# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            Anthony Lloyd
tagline:          ''
description:      ''
url:              http://anthonylloyd.github.io
baseurl:          /

author:
  name:           'Anthony Lloyd'
  url:            http://anthonylloyd.github.io

paginate:         5


github:           http://anthonylloyd.github.io
  repo:           http://anthonylloyd.github.io

gems: [jekyll-paginate]
