# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            Anthony Lloyd
tagline:          ''
description:      'A few of my own ideas on functional software design'
url:              http://anthonylloyd.github.io
baseurl:          /

author:
  name:           'Anthony Lloyd'
  url:            http://anthonylloyd.github.io

paginate:         5


github:
  repo:           http://anthonylloyd.github.io

gems: [jekyll-paginate]
