title: Anthony Lloyd
email: anthony_lloyd@yahoo.com
description: ''
baseurl: http://anthonylloyd.github.io
url: http://anthonylloyd.github.io
twitter_username: AnthonyLloyd123
github_username:  AnthonyLloyd
markdown: kramdown
