# config
markdown:         kramdown
highlighter:      rouge
permalink:        /blog/:year/:month/:day/:title
title:            'Anthony Lloyd'
tagline:          'Functional thoughts'
description:      'Personal blog on functional programming'
url:              http://anthonylloyd.github.io
baseurl:          /
author:
  name:           'Anthony Lloyd'
  url:            http://anthonylloyd.github.io
github:
  repo:           http://anthonylloyd.github.io